"""update model

Revision ID: 1bea2f99c923
Revises: 
Create Date: 2023-12-08 11:12:53.847857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bea2f99c923'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responsavel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nis', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('profissao_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('contatos', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('endereco_logradouro', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('endereco_bairro', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('endereco_cidade', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('obs', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('endereco_numero', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('endereco_localidade', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('data_inscricao', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ctps', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('servidor', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('local', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('endereco_cep', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('endereco_area', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responsavel', schema=None) as batch_op:
        batch_op.drop_column('email')
        batch_op.drop_column('endereco_area')
        batch_op.drop_column('endereco_cep')
        batch_op.drop_column('local')
        batch_op.drop_column('servidor')
        batch_op.drop_column('ctps')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('data_inscricao')
        batch_op.drop_column('endereco_localidade')
        batch_op.drop_column('endereco_numero')
        batch_op.drop_column('obs')
        batch_op.drop_column('endereco_cidade')
        batch_op.drop_column('endereco_bairro')
        batch_op.drop_column('endereco_logradouro')
        batch_op.drop_column('contatos')
        batch_op.drop_column('profissao_id')
        batch_op.drop_column('nis')

    # ### end Alembic commands ###
