"""Initial migration

Revision ID: 391d53035dbd
Revises: 
Create Date: 2023-12-12 11:20:22.710767

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '391d53035dbd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('escola', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endereco_cep', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('endereco_localidade', sa.String(length=100), nullable=True))
        batch_op.drop_column('regulamentacao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('escola', schema=None) as batch_op:
        batch_op.add_column(sa.Column('regulamentacao', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('endereco_localidade')
        batch_op.drop_column('endereco_cep')

    # ### end Alembic commands ###
