"""campos adicionais

Revision ID: 946bb671922e
Revises: 
Create Date: 2023-12-07 11:35:41.136003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '946bb671922e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.add_column(sa.Column('naturalidade_uf', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('endereco_uf', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.drop_column('endereco_uf')
        batch_op.drop_column('naturalidade_uf')

    # ### end Alembic commands ###
