"""migracao inicial

Revision ID: b77a74dfbdc2
Revises: 
Create Date: 2024-02-21 08:00:53.462671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b77a74dfbdc2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aluno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('sexo', sa.String(length=10), nullable=True),
    sa.Column('data_nasc', sa.Date(), nullable=True),
    sa.Column('mae', sa.String(length=100), nullable=True),
    sa.Column('mae_profissao', sa.String(length=100), nullable=True),
    sa.Column('pai', sa.String(length=100), nullable=True),
    sa.Column('pai_profissao', sa.String(length=100), nullable=True),
    sa.Column('naturalidade', sa.String(length=100), nullable=True),
    sa.Column('naturalidade_uf', sa.String(length=10), nullable=True),
    sa.Column('endereco_logradouro', sa.String(length=255), nullable=True),
    sa.Column('endereco_numero', sa.String(length=10), nullable=True),
    sa.Column('endereco_cep', sa.String(length=10), nullable=True),
    sa.Column('endereco_bairro', sa.String(length=100), nullable=True),
    sa.Column('endereco_cidade', sa.String(length=100), nullable=True),
    sa.Column('endereco_uf', sa.String(length=10), nullable=True),
    sa.Column('local_residencia', sa.String(length=100), nullable=True),
    sa.Column('cpf', sa.String(length=15), nullable=True),
    sa.Column('nacionalidade', sa.String(length=50), nullable=True),
    sa.Column('obs', sa.Text(), nullable=True),
    sa.Column('racacor', sa.String(length=50), nullable=True),
    sa.Column('deficiencias', sa.Text(), nullable=True),
    sa.Column('nivel_suporte', sa.String(length=50), nullable=True),
    sa.Column('codigo_cid', sa.String(length=10), nullable=True),
    sa.Column('data_diagnostico', sa.Date(), nullable=True),
    sa.Column('descricao_deficiencia', sa.Text(), nullable=True),
    sa.Column('necessidades_especificas', sa.Text(), nullable=True),
    sa.Column('pasta_id', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('data_inscricao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aluno')
    # ### end Alembic commands ###
