"""Initial migration

Revision ID: 8147a9759ba2
Revises: 
Create Date: 2023-12-11 11:11:01.441877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8147a9759ba2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matricula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ano_letivo', sa.String(length=4), nullable=True),
    sa.Column('aluno_id', sa.Integer(), nullable=True),
    sa.Column('aluno_nome', sa.String(length=255), nullable=True),
    sa.Column('turma_id', sa.Integer(), nullable=True),
    sa.Column('turma_nome', sa.String(length=255), nullable=True),
    sa.Column('turma_turno', sa.String(length=10), nullable=True),
    sa.Column('responsavel_nome', sa.String(length=255), nullable=True),
    sa.Column('responsavel_id', sa.Integer(), nullable=True),
    sa.Column('responsavel_parentesco', sa.String(length=50), nullable=True),
    sa.Column('data_matricula', sa.Date(), nullable=True),
    sa.Column('escola_origem', sa.String(length=255), nullable=True),
    sa.Column('fardamento', sa.String(length=1), nullable=True),
    sa.Column('transporte', sa.String(length=3), nullable=True),
    sa.Column('resultado', sa.String(length=255), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('observacoes', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('pasta_aluno_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matricula')
    # ### end Alembic commands ###
